import type { Metadata } from "next";
import { Source_Sans_3 as FontSans } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/common/footer";
import { Component } from "@/app/components/ui/background-components";

const fontSans = FontSans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata: Metadata = {
  title: "SUMMARIZER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} font-sans antialiased`}
      >

        <Component >
          
          <main className="flex-1">{children}</main>
          <Footer />
        </Component>
        {/* <div className="flex flex-col relative min-h-screen">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
         */}
      </body>
    </html>
  );
}
